### ISSUE TITLE
 ModuleNotFoundError: No module named 'KCSD1D'

### ISSUE THREAD

**Issue by aeladly91** [INCF/pykCSD#9]
Hello,

I am trying to use the pykCSD package. I have successfully installed it using the pip install command. However, when I try to import it using the following line
"from pykCSD.pykCSD import KCSD"

I get module not found error.

Do you know how I can fix this?

Thanks in advance :)

**Comment by danek8317** [comment]
Hi, This module is currently not maintained. We recommend using

kCSD-python : https://github.com/Neuroinflab/kCSD-python

The relevant documentation with extensive tutorials is provided there.

**Comment by ahmeddeladly** [comment]
Thank you so much :)
